### ISSUE TITLE
求一份未修改的原始代码

### ISSUE THREAD

**Issue by hzyfox** [GITHUBear/HustBase_2019#1]
Hello, 同学我也是华科计卓13级的，在读研，想重新做下这个课设回味一下。能不能给我邮箱发一份没有修改的的代码(就是还未补全的代码)。如果附上老师课程设计的说明的资料就更好了。 感谢 我的邮箱 cszhenyuhu@hust.edu.cn

**Comment by minxinhao** [comment]
我们最初的版本就是没有修改的代码，你git下来回溯就行了
